apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: test
spec:
  customizations:
    replicaResource:
      luaScript: |
        function AggregateStatus(desiredObj, statusItems)
        		if  desiredObj.status == nil then
                    desiredObj.status={}
        	        desiredObj.status.readyReplicas = 0
                end

                for i = 1, #statusItems do
                    print(statusItems[i].status.readyReplicas)
                    if  statusItems[i].status.readyReplicas  == nil then
                       statusItems[i].status.readyReplicas = 0
                      end
                    desiredObj.status.readyReplicas = desiredObj.status.readyReplicas + statusItems[i].status.readyReplicas
                end
                return desiredObj
            end
  target:
    apiVersion: apps/v1
    kind: Deployment